// Menu data
export const menuCategories = [
  {
    id: "featured",
    name: "Featured",
    items: [
      {
        id: "signature-pasta",
        name: "Signature Pasta",
        description: "Homemade pasta with our secret sauce, fresh basil, and parmesan",
        price: 18.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["popular", "vegetarian"],
        nutritionalInfo: {
          calories: 650,
          protein: "24g",
          carbs: "82g",
          fat: "22g",
        },
      },
      {
        id: "filet-mignon",
        name: "Filet Mignon",
        description: "Premium cut steak with truffle mashed potatoes and seasonal vegetables",
        price: 32.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["popular", "gluten-free"],
        nutritionalInfo: {
          calories: 720,
          protein: "48g",
          carbs: "35g",
          fat: "38g",
        },
      },
      {
        id: "tiramisu",
        name: "Tiramisu",
        description: "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone cream",
        price: 9.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["popular", "vegetarian"],
        nutritionalInfo: {
          calories: 420,
          protein: "7g",
          carbs: "45g",
          fat: "24g",
        },
      },
    ],
  },
  {
    id: "appetizers",
    name: "Appetizers",
    items: [
      {
        id: "bruschetta",
        name: "Bruschetta",
        description: "Toasted bread topped with fresh tomatoes, garlic, basil, and olive oil",
        price: 10.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["vegetarian"],
        nutritionalInfo: {
          calories: 320,
          protein: "6g",
          carbs: "38g",
          fat: "16g",
        },
      },
      {
        id: "calamari",
        name: "Crispy Calamari",
        description: "Lightly fried calamari served with lemon aioli and marinara sauce",
        price: 14.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: [],
        nutritionalInfo: {
          calories: 480,
          protein: "22g",
          carbs: "42g",
          fat: "24g",
        },
      },
      {
        id: "vegetarian-platter",
        name: "Vegetarian Platter",
        description: "Selection of fresh vegetables, hummus, olives, and pita bread",
        price: 16.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["vegetarian", "vegan", "gluten-free"],
        nutritionalInfo: {
          calories: 420,
          protein: "12g",
          carbs: "58g",
          fat: "18g",
        },
      },
    ],
  },
  {
    id: "main-courses",
    name: "Main Courses",
    items: [
      {
        id: "grilled-salmon",
        name: "Grilled Salmon",
        description: "Fresh salmon fillet with lemon herb butter, wild rice, and asparagus",
        price: 24.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["gluten-free"],
        nutritionalInfo: {
          calories: 580,
          protein: "42g",
          carbs: "32g",
          fat: "28g",
        },
      },
      {
        id: "seafood-risotto",
        name: "Seafood Risotto",
        description: "Creamy arborio rice with shrimp, scallops, and seasonal seafood",
        price: 22.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["gluten-free"],
        nutritionalInfo: {
          calories: 620,
          protein: "28g",
          carbs: "68g",
          fat: "24g",
        },
      },
      {
        id: "vegetable-curry",
        name: "Vegetable Curry",
        description: "Aromatic curry with seasonal vegetables, served with basmati rice",
        price: 17.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["vegetarian", "vegan", "gluten-free"],
        nutritionalInfo: {
          calories: 520,
          protein: "14g",
          carbs: "76g",
          fat: "18g",
        },
      },
      {
        id: "chicken-parmesan",
        name: "Chicken Parmesan",
        description: "Breaded chicken breast topped with marinara sauce and mozzarella, served with pasta",
        price: 19.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: [],
        nutritionalInfo: {
          calories: 780,
          protein: "48g",
          carbs: "64g",
          fat: "32g",
        },
      },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    items: [
      {
        id: "chocolate-lava-cake",
        name: "Chocolate Lava Cake",
        description: "Warm chocolate cake with a molten center, served with vanilla ice cream",
        price: 10.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["vegetarian"],
        nutritionalInfo: {
          calories: 580,
          protein: "8g",
          carbs: "68g",
          fat: "28g",
        },
      },
      {
        id: "cheesecake",
        name: "New York Cheesecake",
        description: "Classic creamy cheesecake with a graham cracker crust and berry compote",
        price: 9.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["vegetarian"],
        nutritionalInfo: {
          calories: 520,
          protein: "10g",
          carbs: "48g",
          fat: "32g",
        },
      },
      {
        id: "sorbet",
        name: "Seasonal Fruit Sorbet",
        description: "Refreshing house-made sorbet with fresh seasonal fruits",
        price: 7.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["vegetarian", "vegan", "gluten-free"],
        nutritionalInfo: {
          calories: 220,
          protein: "0g",
          carbs: "54g",
          fat: "0g",
        },
      },
    ],
  },
  {
    id: "drinks",
    name: "Drinks",
    items: [
      {
        id: "craft-cocktails",
        name: "Craft Cocktails",
        description: "Selection of handcrafted signature cocktails",
        price: 12.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: [],
        nutritionalInfo: {
          calories: 220,
          protein: "0g",
          carbs: "18g",
          fat: "0g",
        },
      },
      {
        id: "wine-selection",
        name: "Wine Selection",
        description: "Curated selection of red, white, and sparkling wines",
        price: 9.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["gluten-free"],
        nutritionalInfo: {
          calories: 150,
          protein: "0g",
          carbs: "4g",
          fat: "0g",
        },
      },
      {
        id: "craft-beer",
        name: "Craft Beer",
        description: "Local and imported craft beers",
        price: 7.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: [],
        nutritionalInfo: {
          calories: 180,
          protein: "2g",
          carbs: "14g",
          fat: "0g",
        },
      },
      {
        id: "non-alcoholic",
        name: "Non-Alcoholic Beverages",
        description: "Fresh juices, specialty sodas, and mocktails",
        price: 4.99,
        image: "/placeholder.svg?height=120&width=120",
        tags: ["non-alcoholic", "vegetarian", "vegan", "gluten-free"],
        nutritionalInfo: {
          calories: 120,
          protein: "0g",
          carbs: "30g",
          fat: "0g",
        },
      },
    ],
  },
]

// Flatten all menu items into a single array for easy lookup
export const allMenuItems = menuCategories.flatMap((category) => category.items)
